# Generated by Django 3.0.3 on 2020-05-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200515_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fooitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('isactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Fooitem1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('isactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Fooitem2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('isactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('para', models.TextField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('gmail', models.CharField(max_length=255)),
                ('headinga', models.CharField(max_length=255)),
                ('headingb', models.CharField(max_length=255)),
                ('headingc', models.CharField(max_length=255)),
                ('paraa', models.CharField(max_length=255)),
                ('parab', models.CharField(max_length=255)),
                ('parac', models.CharField(max_length=255)),
                ('parad', models.CharField(max_length=255)),
                ('isactive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('gmail', models.EmailField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('isactive', models.BooleanField()),
            ],
        ),
    ]
