# Generated by Django 3.0.3 on 2020-05-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fooitem_fooitem1_fooitem2_footer_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('heading', models.CharField(max_length=255)),
                ('headinga', models.CharField(max_length=255)),
                ('btn', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('isactive', models.BooleanField()),
            ],
        ),
    ]
