# Generated by Django 3.0.3 on 2020-05-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart1',
            name='total',
            field=models.IntegerField(),
        ),
    ]
