# Generated by Django 3.0.3 on 2020-06-04 04:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vege', '0006_auto_20200522_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment1',
            new_name='Payment',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment1',
            new_name='payment',
        ),
    ]
