# Generated by Django 3.0.3 on 2020-06-04 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_auto_20200604_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='btn',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='link',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='para',
        ),
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(default='test vege', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vege.Coupon'),
        ),
    ]
