# Generated by Django 3.0.3 on 2020-06-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_auto_20200604_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='isactive',
        ),
    ]
