# Generated by Django 3.0.3 on 2020-06-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_remove_coupon_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(),
        ),
    ]
