# Generated by Django 3.0.3 on 2020-06-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0010_auto_20200609_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
    ]
