# Generated by Django 3.0.3 on 2020-06-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0011_auto_20200609_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(null=True),
        ),
    ]
