from django.contrib import admin
from .models import BillingAddress,Payment, Top,Nav,Drop,Left,Slider,Service,Category,Product,Item1,Oneitem,Test,Testimonial,Pattern,Form,Footer,Fooitem,Fooitem1,Fooitem2,About,Disc,Count,Counter,Blog,Blogdetail,Blogdis,Ccategory,Recblog,Cloud,Food,Thing,Author,Comment,Data,Cart1,Cartdtl,Head,Cart,Coupon,Shipping,Total,Checkot,Option,Contact,Contactinfo,Msg,Singpro,Singleitem,Value,Item,Items,Shop,Categry,Page,Wishlist,Wish,Wishitem,Order,OrderItem
# Register your models here.

admin.site.register(Top)
admin.site.register(Nav)
admin.site.register(Drop)
admin.site.register(Left)
admin.site.register(Slider)
admin.site.register(Service)
admin.site.register(Category)
admin.site.register(Product)
admin.site.register(Item1)
admin.site.register(Oneitem)
admin.site.register(Test)
admin.site.register(Testimonial)
admin.site.register(Pattern)
admin.site.register(Form)
admin.site.register(Footer)
admin.site.register(Fooitem)
admin.site.register(Fooitem1)
admin.site.register(Fooitem2)
admin.site.register(About)
admin.site.register(Disc)
admin.site.register(Count)
admin.site.register(Counter)
admin.site.register(Blog)
admin.site.register(Blogdetail)
admin.site.register(Blogdis)
admin.site.register(Ccategory)
admin.site.register(Recblog)
admin.site.register(Cloud)
admin.site.register(Food)
admin.site.register(Thing)
admin.site.register(Author)
admin.site.register(Comment)
admin.site.register(Data)
admin.site.register(Cart1)
admin.site.register(Cartdtl)
admin.site.register(Head)
admin.site.register(Cart)
admin.site.register(Coupon)
admin.site.register(Shipping)
admin.site.register(Total)
admin.site.register(Checkot)

admin.site.register(Option)


admin.site.register(Contact)
admin.site.register(Contactinfo)
admin.site.register(Msg)
admin.site.register(Singpro)
admin.site.register(Singleitem)
admin.site.register(Value)
admin.site.register(Item)
admin.site.register(Items)
admin.site.register(Shop)
admin.site.register(Categry)

admin.site.register(Page)
admin.site.register(Wishlist)
admin.site.register(Wish)
admin.site.register(Wishitem)

class OrderAdmin(admin.ModelAdmin):
    list_display = ['user','ordered']
admin.site.register(Order,OrderAdmin)
admin.site.register(OrderItem)
admin.site.register(Payment)
admin.site.register(BillingAddress)


